version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3001:3000
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8081:8081
    networks:
      - monitoring

  nginx-config-monitor:
    image: alpine:latest
    volumes:
      - ./nginx-monitoring.conf:/nginx-monitoring.conf:ro
      - /etc/nginx/sites-available:/sites-available
      - /etc/nginx/sites-enabled:/sites-enabled
    command: >
      sh -c "cp -f /nginx-monitoring.conf /sites-available/monitoring.serp24.online &&
             ln -sf /sites-available/monitoring.serp24.online /sites-enabled/monitoring.serp24.online &&
             ls -l /sites-enabled/monitoring.serp24.online"

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring: