global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Use internal port 8080, not 8081
  - job_name: 'jenkins'
    scheme: https  # Explicitly set to HTTPS
    static_configs:
      - targets: ['jenkins.serp24.online:443']  # Use 443 for HTTPS
    metrics_path: /metrics/ihtnl81wTeVq91LEb2quPZwQktMJ9qzS82Y0P_Xw0TSY2wx2zRt_tzxmHnWUEQ6I