global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']
  - job_name: 'jenkins'
    static_configs:
      - targets: ['e4ff7720f799:8080']
